version: "2"
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    restart: always 
    ports:
      - 80:80
    volumes:
      - ./django/public/static:/STATIC
      - ./django/public/media:/MEDIA
      - ./nginx:/etc/nginx/conf.d
      - ./react/build:/var/www/react
    depends_on:
      - django
  django:
    build: ./django
    volumes:
      - ./django:/taakmart
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:

  # react:
  #   image: node:alpine
  #   command: sh entrypoint.sh
  #   working_dir: /react
  #   volumes:
  #     - ./react/:/react