version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./django/public/static:/STATIC
      - ./django/public/media:/MEDIA
      - ./nginx:/etc/nginx/conf.d
      - ./react/build:/var/www/react
    depends_on:
      - django
      - react
  django:
    build: ./django
    volumes:
      - ./django:/taakmart
    command: >
      bash -c '
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic &&
      gunicorn taakmart.wsgi:application --bind 0.0.0.0:8000 --workers 3'
    #    depends_on:
#      - db
  react:
    build: ./react
    volumes:
      - ./react/node_modules:/react/node_modules
      - ./react:/react