# Generated by Django 2.2.8 on 2020-05-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_historicalcompany_historicalseller'),
        ('main', '0012_historicalbrand_historicalcategory_historicalproduct_historicalslide_historicaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Company'),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.Company'),
        ),
    ]
